### ISSUE TITLE
PCKManager omitting files when unpacking Commando 2's DATA.PCK

### ISSUE THREAD

**Issue by chbrehm** [IanusInferus/cmdt#10]
I've recently tried PCKManager.exe as well as the "CoRE - Commandos Resource Extractor v2.0". I used them to fully extract the DATA.PCK and DATA2.PCK from Commandos 2.

Extracting the DATA2.PCK gives the same result for both tools.

However, for DATA.PCK I get different results:
- PCKManager.exe extracts 4,805 files with a total of 615,561,811 bytes
- CoRE 2.0 extracts 5,927 files with a total of 670,979,119 bytes

One example difference: The folder DATA\RED inside of DATA.PCK:
- PCKManager.exe lists and extracts only 1 file called RED.GRL
- CoRE 2.0 lists and extracts 10 files: RED.GRL and 0.JPG, ..., 8.JPG

Is this a bug or might I be doing something wrong?

For reference, I used the PCK files from the Steam version of Commandos 2. The file sizes are as follows:
- DATA.PCK: 620,699,648 bytes
- DATA2.PCK: 336,777,216 bytes

**Comment by chbrehm** [comment]
![2023-10-23-20-05-32_PCKManager_pYomGqCbpr](https://github.com/IanusInferus/cmdt/assets/28632515/9aaa890b-7203-4469-8625-656975d69a90)

![2023-10-23-20-06-04_CoRE_OMz4QwMwEh](https://github.com/IanusInferus/cmdt/assets/28632515/5de30596-8df7-41d3-9040-9e8af9692ae1)

**Comment by chbrehm** [comment]
Update: I've done some reading into the documentation of  the PCK file format and done a little file parsing myself. It seems that PCKManager.exe is actually doing things correctly, and the CoRE tool is buggy. The additional files "extracted" by CoRE seem to be duplicates. For example, the 0.JPG, ..., 8.JPG mentioned above are actually duplicates of the files in the CREDITOS folder.

**Comment by IanusInferus** [comment]
Thank you for your further research.
I'm glad that there is no problem.
