### ISSUE TITLE
DeBsmb: handling of '!'

### ISSUE THREAD

**Issue by chbrehm** [IanusInferus/cmdt#11]
I noticed an inconsistency in the ouput of the DeBsmb tool.

For Commandos 2, the *.GSC files contain script sections. For example, here is an excerpt from PA.GSC after using DeBsmb:

```
	! SETVAR $bCalla FALSE
	! ENDIF
	! ENDIF
	! IF ( ( %GetDificultad ( 0 ) )
	!= 0 )
	! IF (
	! $bHabla )
	! SETVAR $bHabla TRUE
	! PON_ANIMSECUENCIA HABLAR_1

```
It seems the DeBsmb tool prints a line break for every occurence of '!'. However, '!' also appears within the script lines as one of two operators: ! meaning NOT, and != meaning NOT EQUAL. In these cases, the line breaks are undesired.

So instead of:
```
	! IF ( ( %GetDificultad ( 0 ) )
	!= 0 )

```
The output should be:
`	! IF ( ( %GetDificultad ( 0 ) ) != 0 )
`
And instead of:
```
	! IF (
	! $bHabla )

```
It should be:
`	! IF ( ! $bHabla )
`

**Comment by IanusInferus** [comment]
I have fixed this issue in the source code. You can recompile and check if it is fixed.

**Comment by chbrehm** [comment]
I've just tested it using the latest master, and using the PA.GSC file from Commandos 2. It is fixed for both cases I mentioned above.

Thank you for the fast fix.
