### ISSUE TITLE
the program has something wrong - ERROR

### ISSUE THREAD

**Issue by doodien** [IanusInferus/cmdt#12]
this error appears when creating .dir file

![Снимок](https://github.com/IanusInferus/cmdt/assets/157294625/2836c459-f4df-4856-8a74-63a2aba58214)

**Comment by IanusInferus** [comment]
You can check if TEST_STEAM folder exists. If the folder does not exist, the program won't create one by itself.
Other possibilities include access control list settings on the folder.

**Comment by doodien** [comment]
> You can check if TEST_STEAM folder exists. If the folder does not exist, the program won't create one by itself. Other possibilities include access control list settings on the folder.

OK, its done! Thanks, it works
