### ISSUE TITLE
pck file structure

### ISSUE THREAD

**Issue by subabrain** [IanusInferus/cmdt#13]
Hello Girls and Boys,

just wanna ask for the correct structure of a PCK File :) 

Thanks and Regards!
Robert

**Comment by IanusInferus** [comment]
Please check [Doc/Comm2_PCK.en.htm](https://github.com/IanusInferus/cmdt/blob/master/Doc/Comm2_PCK.en.htm) under the repo. (Download it and open in a browser.)
You can also check [FileSystem/Comm2/PCK.vb](https://github.com/IanusInferus/cmdt/blob/master/FileSystem/Comm2/PCK.vb) for more specific implementation.
