### ISSUE TITLE
New Tool to Replace ABI Textures

### ISSUE THREAD

**Issue by subabrain** [IanusInferus/cmdt#2]
https://github.com/subabrain/AbiBmpReplacer - here you can change Textures of ABI Files from Commandos 2.

**Comment by IanusInferus** [comment]
Great work.
I have added your project to "Related Sites and Projects" in the readme file.

**Comment by subabrain** [comment]
thanks!

maybe you can add in your cmdt Project :)

Greets
Robert

**Comment by IanusInferus** [comment]
cmdt is an open-source project. But your project is a closed-source project.

If you want to contribute your source code into cmdt, you can fork cmdt and add your code, then create a pull request.
Notice that cmdt is licensed under the 3-clause BSD license.

If you update frequently, you'd better leave it as a separate project so you can update at any time you want.

**Comment by subabrain** [comment]
thanks,

ok - i will do open source with the next update ;)

Greets
Robert

**Comment by subabrain** [comment]
Hi,

Version 0.7 Beta is out! And with open source:

https://github.com/subabrain/AbiBmpReplacerSource

Greets
Robert

**Comment by subabrain** [comment]
Please add :)

**Comment by IanusInferus** [comment]
Great! You can for my repo and put the code in 'Src' directory and send a pull request to me.
https://docs.github.com/en/get-started/quickstart/fork-a-repo
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

You need also ensure that you want the code to be released under BSD license.

By the way, there are three places that can be improved.
1) Managed DirectX is very old, it's better to not use it.
2) ImageProcessor.Web seems not been used, it's better to remove it.
3) TargetFrameworkVersion v3.5 is old and not installed by default on Windows 10 machines. It's better to use a 4.6.1 or 4.8 target.

**Comment by subabrain** [comment]
okay - i will do my best :)

**Comment by subabrain** [comment]
STOP - Sorry i forgot to handle with 2 or more Entries ... i will post a update soon ...

**Comment by IanusInferus** [comment]
I can change them this time.

**Comment by IanusInferus** [comment]
Your code is merged.
Thanks for your contribution.
I have released a new version with your tool.
If there is any problem, you can reopen this issue or create a new one.
