### ISSUE TITLE
New Version ABI Replacer 0.8 Beta

### ISSUE THREAD

**Issue by subabrain** [IanusInferus/cmdt#4]
Hi there,

the new Version of the ABI BMP Replacer is ready - and some bugs are fixed - please load the new one ...

Greets
Robert

**Comment by IanusInferus** [comment]
Please submit a pull request.

**Comment by subabrain** [comment]
okay - ill do but how can i create a folder in the fork? I forgot ...

Thanks!
Robert

**Comment by IanusInferus** [comment]
I suggest you first `git reset` your master to IanusInferus:master. You can then replace files from that point.
Then you can commit and forcefully push your commit to github with `git push -f`.

**Comment by IanusInferus** [comment]
Or you can delete your fork and create it again. Then clone it again.

**Comment by subabrain** [comment]
ok - allright :)

**Comment by IanusInferus** [comment]
Corresponding pull request #5 has been merged.
