### ISSUE TITLE
Commandos 3 HD Remaster .pack

### ISSUE THREAD

**Issue by tSlappy** [IanusInferus/cmdt#6]
Can you add support for C3 HD remaster .pak format?

See https://zenhax.com/viewtopic.php?f=9&t=17364 for details and attached files

**Comment by IanusInferus** [comment]
I haven't bought C3 HD remaster and I don't plan to buy it recently.

**Comment by tSlappy** [comment]
> I haven't bought C3 HD remaster and I don't plan to buy it recently.

If you have a Steam or Epic account you can get the Demo on both platforms, which is free.

**Comment by IanusInferus** [comment]
I downloaded the demo. I believe there is no file names in the package.

**Comment by IanusInferus** [comment]
00000000 or 80000000 indicates compression(SDPC).
I think you are right with the LZ guess.
For literal data, a prefix byte 0? looks like (length of literal data - 3).
05 5     8
09 9     12
0B 11    14
0F 15    18

**Comment by IanusInferus** [comment]
I have found some patterns.

0X(01~0F) -> (X+3) literal count
00 XX -> (XX+18) literal count
LLL????B ??????LL (ZZ)? -> (LLLLL+1) length, B wether a literal byte is followed

**Comment by IanusInferus** [comment]
I have followed herbert3000's findings in the post and added support of .pak formats.
You can get the new tool at https://github.com/IanusInferus/cmdt/releases/tag/v20220910 .

**Comment by IanusInferus** [comment]
There is a problem with the retail version file.
I have fixed it in https://github.com/IanusInferus/cmdt/releases/tag/v20220910_1 .
