### ISSUE TITLE
In FileDB class, Unknown1 and Unknown2 field is not int32. It should be single int64 field.

### ISSUE THREAD

**Issue by redplcs** [IanusInferus/cmdt#7]
According to ProcessMonitor, which allows you to check WinApi calls, the game reads null-terminated string, two int32, and one int64.

The FileDB class should be:
```vb
Public Class FileDB
    Public Name as String
    Public Address as Int32
    Public Length as Int32
    Public Unknown1 as Int64
    ...
```

![image](https://user-images.githubusercontent.com/51379496/196477188-93ae4a90-7b11-40b7-b2b7-0a66d7ea635d.png)

**Comment by IanusInferus** [comment]
Thank you. I have changed them to a single Int64 field.

**Comment by redplcs** [comment]
Just want to mention. This int64 is not checksum. I've checked all available checksums and noone matches the value.

ps: sorry for opening the issue!
ps2: i can not prove my words because i already closed the editor. i will send it tomorrow if you want
ps3: well it's not opened. forget about ps1

**Comment by IanusInferus** [comment]
My guess is that it is some kind of hash code for the file path to accelerate the process to find a file by path.

**Comment by redplcs** [comment]
Isn't hashcode a checksum? Anyway, I'm reverse engineering the game, so I will tell what exactly these fields are. I'm telling about my progress in our [speedrun discord server](https://discord.gg/BegFpdVF)

**Comment by IanusInferus** [comment]
Hash code is used for string dictionary query. Checksum is for data integrity verification.
They can be implemented similarly, but they are different concepts.
If it is really hash code, there should be code in CSF program that calculate hash code when querying file data from a path.
