### ISSUE TITLE
Commandos strike force

### ISSUE THREAD

**Issue by Snouf-ID** [IanusInferus/cmdt#8]
Hello.
First, thank you for your work.
I'm trying to recover strike force commando maps.
I tried all the tools in .exe but nothing helped.
Can you confirm that this is not supported?
Thanks in advance.
![image](https://user-images.githubusercontent.com/47319640/209211900-1af4c26e-76f1-49a5-ba2e-affe65b0db7f.png)
![image](https://user-images.githubusercontent.com/47319640/209211932-3513d91d-9ced-427d-bacf-37748b432791.png)

**Comment by IanusInferus** [comment]
The only supported file format is PAK in PCKManager. Other strike force formats are not supported.

**Comment by Snouf-ID** [comment]
Very well.
It is indeed a .pak extracted thanks to your tool. But the formats that come out are those of the image above.
From what I understand from your message, these formats then are not openable, viewable with tools of this rest. Thank you for answering.

**Comment by redplcs** [comment]
@Snouf-ID You definitely should ask SOMYST from https://discord.gg/JdMpvP7Z. Currently we can make custom missions on top of existings levels and he's the one who worked with internal files very closely.
