### ISSUE TITLE
有关盟军2打包PCK的问题

### ISSUE THREAD

**Issue by nbct666** [IanusInferus/cmdt#9]
使用PCKmanager的过程中，我发现DATA.PCK解压之后再原模原样压缩回去居然莫名少了10KB，然后comm2.exe也无法运行，是PCKmanager有bug还是我操作有什么问题？
![image](https://user-images.githubusercontent.com/123817348/215270337-34680ca5-9cb8-455d-8e91-5ed0ee302500.png)

**Comment by IanusInferus** [comment]
PCK中有一些没有使用的空间，的确有可能会变更小的。可以把第一次解压出来的文件和第二次解压出来的文件进行比较来看是不是有文件导入有问题。
comm2.exe无法运行有没有可能是因为文件还被PCKManager或者其他工具打开着无法读取导致的？

**Comment by nbct666** [comment]
感谢你及时的回答。为了验证这个问题，我先去重启了一下电脑再打包，结果反倒出现了下图，尚不清楚什么原因。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "IanusInferus/cmdt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月28日(星期六) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IanusInferus/cmdt] 有关盟军2打包PCK的问题 (Issue #9)





 
PCK中有一些没有使用的空间，的确有可能会变更小的。可以把第一次解压出来的文件和第二次解压出来的文件进行比较来看是不是有文件导入有问题。
 comm2.exe无法运行有没有可能是因为文件还被PCKManager或者其他工具打开着无法读取导致的？

**Comment by IanusInferus** [comment]
看不到图

**Comment by nbct666** [comment]
程序出现错误




System.IO.IOException:
文件“C:\Users\hp\Desktop\0129\6.PCK”正由另一进程使用，因此该进程无法访问此文件。


System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) : IL 01D7, N 0000E3
System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) : IL 03A0, N 0002E2
System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) : IL 0000, N 000044
FileSystem.PCK..ctor(String Source, String Path, Version VersionSign) : IL 00CC, N 0002EF
PCKManager.PCKManager.Menu_File_Create2_Click(Object sender, EventArgs e) : IL 00AF, N 00015C
System.Windows.Forms.MenuItem.OnClick(EventArgs e) : IL 0056, N 000075
System.Windows.Forms.MenuItem+MenuItemData.Execute() : IL 0008, N 00002B
System.Windows.Forms.Command.Invoke() : IL 0011, N 00002C
System.Windows.Forms.Command.DispatchID(Int32 id) : IL 000C, N 00001C
System.Windows.Forms.Control.WmCommand(Message&amp; m) : IL 003B, N A7DCBA
System.Windows.Forms.Control.WndProc(Message&amp; m) : IL 031F, N 000385
System.Windows.Forms.ScrollableControl.WndProc(Message&amp; m) : IL 0034, N 000030
System.Windows.Forms.Form.WndProc(Message&amp; m) : IL 02D0, N 000076
System.Windows.Forms.Control+ControlNativeWindow.OnMessage(Message&amp; m) : IL 0000, N 000012
System.Windows.Forms.Control+ControlNativeWindow.WndProc(Message&amp; m) : IL 008E, N 000034
System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) : IL 0025, N 00007F
System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) : IL 0041, N 0000AF
System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG&amp; msg) : N 000000
System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData) : IL 0228, N 00025F
System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context) : IL 01E9, N 000175
System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context) : IL 0014, N 00004F
System.Windows.Forms.Application.Run(Form mainForm) : IL 0011, N 000035
PCKManager.PCKManager.MainWindow() : IL 0038, N 00009E
PCKManager.PCKManager.MainInner() : IL 0027, N 000071
PCKManager.PCKManager.Main() : IL 0010, N 00002E







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IanusInferus/cmdt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月29日(星期天) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IanusInferus/cmdt] 有关盟军2打包PCK的问题 (Issue #9)





 
看不到图

**Comment by IanusInferus** [comment]
这个就是文件被程序锁定了。一般用LockHunter可以确定是什么程序锁定了文件。

**Comment by nbct666** [comment]
好的，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IanusInferus/cmdt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月29日(星期天) 晚上6:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IanusInferus/cmdt] 有关盟军2打包PCK的问题 (Issue #9)





 
这个就是文件被程序锁定了。一般用LockHunter可以确定是什么程序锁定了文件。
